spring.application.name=koushien_backend
# 接続先URL（jdbc:postgresql://ホスト名:ポート/データベース名）
spring.datasource.url=jdbc:postgresql://localhost:5432/koushien

# データベースのユーザー名とパスワード
spring.datasource.username=user
spring.datasource.password=

# Hibernate・JPAの設定
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
